version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - finance-network

  account-service:
    build:
      context: ./account-service
    container_name: account-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/accountdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    networks:
      - finance-network

  classifier-service:
    build:
      context: ./classifier-service
    container_name: classifier-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/classifierdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    networks:
      - finance-network

  audit-service:
    build:
      context: ./audit-service
    container_name: audit-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auditdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  postgres_data: