server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auditdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: mySecretKey
  expiration: 3600000
