server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret: //тут ключ
  expiration: 3600000