server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mail.ru
    port: 587
    username: @mail.ru
    password:
    from: @mail.ru
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
jwt:
  secret: ba0e7f4583a1a3d73fa06c31fd846dac0913f875fc3d538bdf1409b2f953f385
  expiration: 3600000
